# Generated by Django 4.2.6 on 2023-10-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
